url: "http://acceptableriskla.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog

# Site settings
title: Acceptable Risk LA
email: acceptableriskla@gmail.com
description: "Acceptable Risk LA (ARLA) is a Los-Angeles based arts collective founded in 2019."
copyright: 2019 Acceptable Risk LA, All Rights Reserved.

# Team names, titles and social links
people:
- name: <a href = "http://www.emilybabette.com">Emily Babette</a>
  pic: 1
  #position: 
  social:
    - title: laptop
      url: 'http://www.emilybabette.com'
    - title: instagram
      url: 'https://www.instagram.com/emilybabette/'

- name: <a href = "https://cargocollective.com/GabbahBaya">Gabbah Baya</a>
  pic: 2
  #position:
  social:
    - title: laptop
      url: 'https://cargocollective.com/GabbahBaya'
    - title: instagram
      url: 'https://www.instagram.com/gabbahbaya/'

- name: <a href = "http://www.carlychubak.com">Carly Chubak</a>
  pic: 3
  #position:
  social:
    - title: laptop
      url: 'http://www.carlychubak.com/'
    - title: instagram
      url: 'https://www.instagram.com/whatcarlysees/'

- name: <a href = "https://seacully.com/">Sean Cully</a>
  pic: 4
  #position:
  social:
    - title: laptop
      url: 'https://seacully.com'
    - title: instagram
      url: 'https://www.instagram.com/seacully/'

- name: <a href = "https://centralserver.biz/">Joshua Oduga</a>
  pic: 5
  #position:
  social:
    - title: laptop
      url: 'https://centralserver.biz/'
    - title: instagram
      url: 'https://www.instagram.com/tundeoduga/'

- name: <a href = "http://stephaniesherwoodart.com/">Stephanie Sherwood</a>
  pic: 6
  #position:
  social:
    - title: laptop
      url: 'http://stephaniesherwoodart.com/'
    - title: instagram
      url: 'https://www.instagram.com/stephanie_sherwood_art/'

- name: <a href = "http://www.kshanks.com/">Katie Shanks</a>
  pic: 7
  #position:
  social:
    - title: laptop
      url: 'http://www.kshanks.com/'
    - title: instagram
      url: 'https://www.instagram.com/art.kshanks/'

- name: <a href = "http://katesikorski.com/">Kate Sikorski</a>
  pic: 8
  #position:
  social:
    - title: laptop
      url: 'http://katesikorski.com/'
    - title: instagram
      url: 'https://www.instagram.com/kate_sikorski/'

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: https://www.instagram.com/acceptableriskla/
  - title: facebook
    url: https://www.facebook.com/acceptableriskla/

      
      
# Postal address (add as many lines as necessary)
address:
  - line: Various Locations
  - line: Los Angeles, CA

# Build settings
markdown: kramdown
permalink: pretty