# Site settings
# in the templates available like {{ site.myvariable }}.
title: Acceptable Risk LA
email: acceptableriskla@gmail.com
brand: Acceptable Risk LA
headline: Los Angeles-based Art Collective
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://acceptableriskla.com" # the base hostname & protocol for your site
copyright: 2018 Acceptable Risk LA, All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 646873

# Contacts
email: acceptableriskla@gmail.com
# phone: +1-800-555-2016

# Tracking
googleAnalitycsID: UA-132567903-1

